### ISSUE TITLE
Errors in \cite{...} command with multiple citations

### ISSUE THREAD

**Issue by martinceresa** [sistedes/sistedes.cls#8] opened 2024-02-09 07:20 UTC
Hi, I think a package may be missing for correct bibtex compilation *when multicitation is used*.

Example:
```latex
 operating
system~\cite{Lee2007, Liu2006, Burns2009}.
```
Generates the following error:
```bash
White space in argument---line 34 of file main.aux
 : \citation{Lee2007,
 :                    Liu2006, Burns2009}
```

To solve it, I just added another package:
```latex
\usepackage{cite}
```

**Comment by abelgomez** [comment] 2024-02-09 12:28
Hi @martinceresa , 

the Sistedes template does not change anything regarding citations and the `llncs` template.

In `llncs`, spaces are not allowed in the `\cite{...}` command. You should use `\cite{Lee2007,Liu2006,Burns2009}` instead. Notice that, for example, `\cite{ Lee2007 }` or `\cite{Lee2007 }` also fail to compile (and they are not multiple citations!).

Removing the spaces should make the `cite` package unnecessary.

I'm closing this since this is expected behavior. Cheers!

**Closed as completed by abelgomez** 2024-02-09 12:28 UTC
Labels: invalid
